services:
  - type: web
    name: fake-news-detector-api
    runtime: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0